# Generated by Django 4.2.7 on 2024-11-21 09:34

import Purchase.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Settings', '0001_initial'),
        ('Product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_no', models.CharField(default=Purchase.models.generate_purchase_no, max_length=50)),
                ('invoice_no', models.CharField(default=Purchase.models.generate_invoice_no, max_length=50)),
                ('purchase_date_time', models.DateTimeField(default=Purchase.models.get_current_date_and_time)),
                ('purchase_date', models.DateField(default=Purchase.models.get_current_date)),
                ('total_item', models.IntegerField()),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('grand_total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Settings.supplier')),
            ],
            options={
                'db_table': 'purchase',
            },
        ),
        migrations.CreateModel(
            name='PurchaseDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bdtRate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.IntegerField()),
                ('linePrice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Product.product')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='purchase_details', to='Purchase.purchase')),
            ],
            options={
                'db_table': 'purchase_details',
            },
        ),
    ]
