# Generated by Django 4.2.7 on 2024-09-23 12:37

import Product.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'brand',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/images/category')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'unit',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(default=Product.models.generate_product_id, max_length=25, unique=True)),
                ('status', models.BooleanField(default=True)),
                ('product_type', models.CharField(max_length=25)),
                ('name', models.CharField(max_length=255)),
                ('product_code', models.CharField(max_length=25, unique=True)),
                ('unit_quantity', models.CharField(max_length=25)),
                ('isFeatureProducts', models.BooleanField(default=False)),
                ('isTopSellingProducts', models.BooleanField(default=False)),
                ('isNewArrivalProducts', models.BooleanField(default=False)),
                ('purchase_stock', models.IntegerField(default=0)),
                ('purchase_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('initial_stock', models.IntegerField(default=0)),
                ('regularPrice', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('specialPrice', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('sizes', models.JSONField(blank=True, null=True)),
                ('colors', models.JSONField(blank=True, null=True)),
                ('mainImage', models.ImageField(blank=True, null=True, upload_to='uploads/images/product')),
                ('sliderImage1', models.ImageField(blank=True, null=True, upload_to='uploads/images/product')),
                ('sliderImage2', models.ImageField(blank=True, null=True, upload_to='uploads/images/product')),
                ('sliderImage3', models.ImageField(blank=True, null=True, upload_to='uploads/images/product')),
                ('sliderImage4', models.ImageField(blank=True, null=True, upload_to='uploads/images/product')),
                ('sliderImage5', models.ImageField(blank=True, null=True, upload_to='uploads/images/product')),
                ('details', models.TextField(blank=True, null=True)),
                ('specification', models.TextField(blank=True, null=True)),
                ('qa', models.TextField(blank=True, null=True)),
                ('review', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Product.brand')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Product.category')),
                ('unit_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Product.unit')),
            ],
            options={
                'db_table': 'product',
            },
        ),
    ]
