# Generated by Django 4.2.7 on 2024-11-21 09:34

import Settings.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=25)),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/images/client')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'client',
            },
        ),
        migrations.CreateModel(
            name='Courier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courier_id', models.CharField(default=Settings.models.generate_courier_id, max_length=25, unique=True)),
                ('status', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'courier',
            },
        ),
        migrations.CreateModel(
            name='DeliveryType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duration', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'delivery_type',
            },
        ),
        migrations.CreateModel(
            name='GeneralSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('company_phone', models.CharField(blank=True, max_length=25, null=True)),
                ('company_email', models.CharField(blank=True, max_length=55, null=True)),
                ('company_address', models.TextField(blank=True, null=True)),
                ('map_url', models.TextField(blank=True, null=True)),
                ('facebook_url', models.TextField(blank=True, null=True)),
                ('instagram_url', models.TextField(blank=True, null=True)),
                ('twitter_url', models.TextField(blank=True, null=True)),
                ('linkedin_url', models.TextField(blank=True, null=True)),
                ('company_logo', models.ImageField(blank=True, null=True, upload_to='uploads/images/general_settings')),
                ('receipt_header', models.TextField(blank=True, null=True)),
                ('receipt_footer', models.TextField(blank=True, null=True)),
                ('theme', models.CharField(blank=True, max_length=25, null=True)),
                ('homeBannerImage1', models.ImageField(blank=True, null=True, upload_to='uploads/images/general_settings')),
                ('homeBannerImage2', models.ImageField(blank=True, null=True, upload_to='uploads/images/general_settings')),
                ('homeBannerImage3', models.ImageField(blank=True, null=True, upload_to='uploads/images/general_settings')),
                ('homeBannerCoverImage', models.ImageField(blank=True, null=True, upload_to='uploads/images/general_settings')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'general_settings',
            },
        ),
        migrations.CreateModel(
            name='StaticDataType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'static_data_type',
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_id', models.CharField(default=Settings.models.generate_supplier_id, max_length=25, unique=True)),
                ('status', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('phone', models.CharField(max_length=25)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='uploads/images/supplier')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'supplier',
            },
        ),
        migrations.CreateModel(
            name='StaticData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Settings.staticdatatype')),
            ],
            options={
                'db_table': 'static_data',
            },
        ),
    ]
